=== VeresMarchello/JEDU1NxmlGyak/XMLFeladat/VM_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">
    <xs:element name="konyvtar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nev" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="cim" minOccurs="0" maxOccurs="1" type="xs:string" />
                
                <xs:element name="kolcsonzo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" minOccurs="0" maxOccurs="1" type="xs:string" />
                            <xs:element name="cim" minOccurs="0" maxOccurs="1" type="xs:string" />
                            <xs:element name="kolcsonzes_kezdete" minOccurs="0" maxOccurs="1" type="xs:date" />
                            <xs:element name="kolcsonzes_vege" minOccurs="0" maxOccurs="1" type="xs:date" />
                        </xs:sequence>
                        <xs:attribute name="azonosito" type="xs:int" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="konyv">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" minOccurs="0" maxOccurs="1" type="xs:string" />
                            <xs:element name="ar" minOccurs="0" maxOccurs="1" type="xs:int" />
                            <xs:element name="oldalszam" minOccurs="0" maxOccurs="1" type="xs:int" />

                            <xs:element name="kiado">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="cim" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="weboldal" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="kiadas" minOccurs="0" maxOccurs="1" type="xs:date" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="szerzo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="szerzodes" minOccurs="0" maxOccurs="1" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="azonosito" type="xs:int" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="isbn" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="azonosito" type="xs:int" />
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="isbn">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d{10,10}" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== VeresMarchello/JEDU1NxmlGyak/XMLFeladat/VM_XML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><konyvtar xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" azonosito="1" xsi:schemaLocation="https://www.w3schools.com VM_XMLSchema.xsd">
    <nev>Rakoczi Megyei Konyvtar</nev>
    <cim>3500 Miskolc, Gorgey Artur 765</cim>

    <kolcsonzo azonosito="1">
        <nev>Kiss Pista</nev>
        <cim>2345 Kukutyin, Arany utca 56</cim>
        <kolcsonzes_kezdete>2019-07-07</kolcsonzes_kezdete>
        <kolcsonzes_vege>2020-03-03</kolcsonzes_vege>
    </kolcsonzo>

    <konyv isbn="0123456789">
        <cim>Egri Csillagok</cim>
        <ar>2300</ar>
        <oldalszam>300</oldalszam>

        <kiado>
            <nev>LegjobbKiado</nev>
            <cim>4560 Balaton, Fo utca 23</cim>
            <weboldal>www.legjobbkiado.hu</weboldal>
            <kiadas>1976-01-06</kiadas>
        </kiado>

        <szerzo azonosito="1">
            <nev>Gardonyi Geza</nev>
            <szerzodes>LegjobbKiado</szerzodes>
        </szerzo>
    </konyv>

</konyvtar>
